### ISSUE TITLE
Identify waveform standardized format

### ISSUE THREAD

**Issue by CmCC1435** [chorus-ai/Tooling-Team#8]

**Comment by briangow** [comment]
On June 13th, 2024 the waveform working group met and recommended WFDB as the base format for waveforms in CHoRUS. This recommendation was based on an assessment of the requirements identified (based on user stories), the benchmarking results, and the state of the specification for the format. 

WFDB was recommended because it met most of the requirements, performed well during benchmarking, and has a complete specification.
